[package]
name = "rust-container"
version = "0.1.0"
authors = ["luke caradine"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
